# KAIST Summer Session 2018

## PyTorch Tutorial in 10 Minutes

1. Create a Tensor
2. Conversion of Tensor Type
3. Reshape a Tensor
4. Indexing, Slicing, Joining
5. Scalar Operation
6. Matrix Operation

## 1. Create a Tensor

In [190]:
import torch
import numpy as np

x = torch.Tensor(2, 3)

torch.is_tensor(x)
print(x)

tensor([[-0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])


In [191]:
z = torch.arange(12)
print(z)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [192]:
z = torch.zeros(5, 2)
print(z)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [193]:
z = torch.ones(2, 3, 2)
print(z)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])


In [194]:
z = torch.eye(3)              # Create an identity 3x3 tensor
print(z)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [195]:
v = torch.rand(4, 3)
z = torch.diag(v)

print(v)
print(z)

tensor([[0.7610, 0.7302, 0.1720],
        [0.2518, 0.4020, 0.6277],
        [0.5947, 0.2671, 0.4621],
        [0.3804, 0.3797, 0.1845]])
tensor([0.7610, 0.4020, 0.4621])


## 2. Conversion of Tensor Type

In [196]:
a = np.array([1, 2, 3])
v = torch.from_numpy(a)         # Convert a numpy array to a Tensor

b = v.numpy()                   # Tensor to numpy

c = x.tolist()

print(type(b))
print(type(c))

<class 'numpy.ndarray'>
<class 'list'>


In [197]:
x1 = torch.Tensor(2, 3)  # An un-initialized Tensor object. x holds garbage data.
x2 = torch.LongTensor(2, 3)  # An un-initialized Tensor object. x holds garbage data.

print(x1.type())
print(x2.type())

torch.FloatTensor
torch.LongTensor


## 3. Reshape a Tensor

In [198]:
### Tensor resizing
v = torch.randn(2, 3)
z1 = v.view(6)
z2 = v.view(-1, 2)                # Size -1 is inferred from other dimensions
z3 = v.view(2, -1)

print(z1.size())
print(z2.size())
print(z3.size())

torch.Size([6])
torch.Size([3, 2])
torch.Size([2, 3])


In [199]:
v = torch.rand(4, 3)
z = torch.transpose(v, 0, 1)

print(v.size())
print(z.size())

torch.Size([4, 3])
torch.Size([3, 4])


In [200]:
v = torch.ones(2,1,2,1) # Size 2x1x2x1
print(v.size())

z = torch.squeeze(v)     # Size 2x2
print(z.size())

z = torch.squeeze(v, 3)  # Squeeze dimension 1: Size 2x2x1
print(z.size())

torch.Size([2, 1, 2, 1])
torch.Size([2, 2])
torch.Size([2, 1, 2])


In [201]:
# Un-squeeze a dimension
v = torch.Tensor([1, 2, 3])
print(v.size())

z = torch.unsqueeze(v, 0)       # Size: 1x3
print(z.size())

z = torch.unsqueeze(v, 1)       # Size: 3x1
print(z.size())

torch.Size([3])
torch.Size([1, 3])
torch.Size([3, 1])


## 4. Indexing, Slicing, Joining

In [202]:
# Indexing
z = torch.zeros(3, 4)

z[:, 1] = 1 
print(z)

tensor([[0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.]])


In [203]:
# Slicing
z = torch.rand(2, 4, 8)
print(z)
print(z[:, 1, :3])
print(z[1, 2])

tensor([[[0.2882, 0.7961, 0.1011, 0.0211, 0.8571, 0.2559, 0.9829, 0.3503],
         [0.9328, 0.8172, 0.7712, 0.4994, 0.8917, 0.6409, 0.7610, 0.9837],
         [0.3467, 0.6368, 0.8894, 0.4239, 0.1294, 0.7086, 0.1711, 0.2334],
         [0.6649, 0.3257, 0.0627, 0.4348, 0.0902, 0.3297, 0.4055, 0.9349]],

        [[0.6395, 0.8397, 0.1971, 0.1172, 0.6482, 0.2229, 0.7168, 0.8317],
         [0.3380, 0.2950, 0.3518, 0.1657, 0.9644, 0.3993, 0.1787, 0.2202],
         [0.7506, 0.4540, 0.7031, 0.5520, 0.2781, 0.6609, 0.2154, 0.8781],
         [0.3794, 0.1278, 0.6450, 0.0076, 0.6908, 0.0813, 0.2757, 0.4725]]])
tensor([[0.9328, 0.8172, 0.7712],
        [0.3380, 0.2950, 0.3518]])
tensor([0.7506, 0.4540, 0.7031, 0.5520, 0.2781, 0.6609, 0.2154, 0.8781])


In [204]:
# Concatenation
v = torch.rand(4, 3)
print(v)

z = torch.cat((v, v), dim=1)          # Concatenate in the 1 dimension

print(z)
print(z.size())

tensor([[0.2528, 0.3416, 0.5269],
        [0.4569, 0.7130, 0.9028],
        [0.6171, 0.5154, 0.2063],
        [0.8663, 0.7373, 0.8843]])
tensor([[0.2528, 0.3416, 0.5269, 0.2528, 0.3416, 0.5269],
        [0.4569, 0.7130, 0.9028, 0.4569, 0.7130, 0.9028],
        [0.6171, 0.5154, 0.2063, 0.6171, 0.5154, 0.2063],
        [0.8663, 0.7373, 0.8843, 0.8663, 0.7373, 0.8843]])
torch.Size([4, 6])


In [205]:
# Stack
v = torch.rand(4, 3)
print(v)

z = torch.stack((v, v))
print(z)
print(z.size())

tensor([[0.7197, 0.4316, 0.6790],
        [0.4198, 0.9202, 0.8132],
        [0.8962, 0.4277, 0.2720],
        [0.3229, 0.1924, 0.7459]])
tensor([[[0.7197, 0.4316, 0.6790],
         [0.4198, 0.9202, 0.8132],
         [0.8962, 0.4277, 0.2720],
         [0.3229, 0.1924, 0.7459]],

        [[0.7197, 0.4316, 0.6790],
         [0.4198, 0.9202, 0.8132],
         [0.8962, 0.4277, 0.2720],
         [0.3229, 0.1924, 0.7459]]])
torch.Size([2, 4, 3])


In [206]:
# Gather element
v = torch.rand(4, 3)
print(v)

z = torch.gather(v, 1, torch.LongTensor([[0,1],[1,0],[2,1],[0,2]]))
print(z)
print(z.size())

z = torch.gather(v, 0, torch.LongTensor([[0,1,1],[1,0,1],[2,2,3]]))
print(z)
print(z.size())

tensor([[0.5646, 0.9691, 0.9947],
        [0.8001, 0.3135, 0.0287],
        [0.4592, 0.8205, 0.4740],
        [0.5752, 0.8081, 0.6177]])
tensor([[0.5646, 0.9691],
        [0.3135, 0.8001],
        [0.4740, 0.8205],
        [0.5752, 0.6177]])
torch.Size([4, 2])
tensor([[0.5646, 0.3135, 0.0287],
        [0.8001, 0.9691, 0.0287],
        [0.4592, 0.8205, 0.6177]])
torch.Size([3, 3])


In [207]:
# Split a tensor into 3 chunks
v = torch.rand(4, 3)
print(v)

z = torch.chunk(v, 3)

print(z)

tensor([[0.5490, 0.8908, 0.2415],
        [0.6069, 0.8836, 0.5979],
        [0.6927, 0.8306, 0.9641],
        [0.0633, 0.3622, 0.4232]])
(tensor([[0.5490, 0.8908, 0.2415],
        [0.6069, 0.8836, 0.5979]]), tensor([[0.6927, 0.8306, 0.9641],
        [0.0633, 0.3622, 0.4232]]))


In [208]:
# Max element with corresponding index
v = torch.rand(4, 3)
print(v)

z = torch.max(v, 1)
print(z)

z = torch.topk(v, 1)
print(z)

tensor([[0.6753, 0.3142, 0.8349],
        [0.6868, 0.2983, 0.8290],
        [0.9174, 0.0698, 0.5925],
        [0.2447, 0.5656, 0.0252]])
(tensor([0.8349, 0.8290, 0.9174, 0.5656]), tensor([2, 2, 0, 1]))
(tensor([[0.8349],
        [0.8290],
        [0.9174],
        [0.5656]]), tensor([[2],
        [2],
        [0],
        [1]]))


In [209]:
# Index select
v = torch.rand(4, 3)
print(v)

indices = torch.LongTensor([0, 2])
z = torch.index_select(v, 1, indices) # Select element 0 and 2 for each dimension 1.

print(z)

tensor([[0.7468, 0.7995, 0.9537],
        [0.5712, 0.0347, 0.4422],
        [0.7870, 0.5964, 0.1553],
        [0.1723, 0.9310, 0.9327]])
tensor([[0.7468, 0.9537],
        [0.5712, 0.4422],
        [0.7870, 0.1553],
        [0.1723, 0.9327]])


## 5. Scalar Operation

In [210]:
v= torch.FloatTensor([[-1, -2, 3], [3, 2, -1], [0.1, 0.4, -0.6]])
print(v)

# absolute value
z = torch.abs(v)      
print(z)

tensor([[-1.0000, -2.0000,  3.0000],
        [ 3.0000,  2.0000, -1.0000],
        [ 0.1000,  0.4000, -0.6000]])
tensor([[1.0000, 2.0000, 3.0000],
        [3.0000, 2.0000, 1.0000],
        [0.1000, 0.4000, 0.6000]])


In [211]:
# Add x, y and scalar 10 to all elements
z = torch.add(v, 10)
print(z)

tensor([[ 9.0000,  8.0000, 13.0000],
        [13.0000, 12.0000,  9.0000],
        [10.1000, 10.4000,  9.4000]])


In [212]:
# Element-wise multiple
z = torch.mul(v, v)
print(z)

tensor([[1.0000, 4.0000, 9.0000],
        [9.0000, 4.0000, 1.0000],
        [0.0100, 0.1600, 0.3600]])


In [213]:
# Element-wise divide
z = torch.div(v, 2*v)
print(z)

tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]])


In [214]:
# Clamp the value of a Tensor
z = torch.clamp(v, min=-0.5, max=0.5)
print(z)

tensor([[-0.5000, -0.5000,  0.5000],
        [ 0.5000,  0.5000, -0.5000],
        [ 0.1000,  0.4000, -0.5000]])


## 6. Matrix Operation

- Dot product of 2 tensors

In [215]:
z = torch.dot(torch.Tensor([4, 2]), torch.Tensor([3, 1]))

print(z)

tensor(14.)


- Matrix by Vector products

In [216]:
# Matrix X vector
mat = torch.randn(2, 4)
vec = torch.randn(4)

z = torch.mv(mat, vec)
print(z.size())

# Matrix + Matrix X vector
M = torch.randn(3)
mat = torch.randn(3, 5)
vec = torch.randn(5)

z = torch.addmv(M, mat, vec)
print(z.size())

torch.Size([2])
torch.Size([3])


- Matrix by Matrix products

In [217]:
# Matrix x Matrix
mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 4)

z = torch.mm(mat1, mat2)
print(z.size())

# Matrix + Matrix X Matrix
M = torch.randn(3, 4)
mat1 = torch.randn(3, 2)
mat2 = torch.randn(2, 4)

z = torch.addmm(M, mat1, mat2)
print(z.size())

torch.Size([2, 4])
torch.Size([3, 4])


- Batch Matrix by Matrix products

In [218]:
# Batch Matrix x Matrix
batch1 = torch.randn(10, 3, 4)
batch2 = torch.randn(10, 4, 5)

z = torch.bmm(batch1, batch2)
print(z.size())

# Batch Matrix + Matrix x Matrix
# 3x4 + (5x3x4 X 5x4x2 ) -> 5x3x2
M = torch.randn(3, 2)
batch1 = torch.randn(5, 3, 4)
batch2 = torch.randn(5, 4, 2)

z = torch.addbmm(M, batch1, batch2)
print(z.size())

torch.Size([10, 3, 5])
torch.Size([3, 2])
