# KAIST Summer Session 2018

## Python Tutorial in 10 Minutes

1. Hellow World!
2. List
3. Dictionary
4. Loop
5. Condition
6. Function
7. Class and Inheritance
8. Module
9. Exception

## 1. Hellow World!

In [5]:
print('Hello World!')
print('Welcome to KAIST Summer Session!')

Hello World!
Welcome to KAIST Summer Session!


## 2. List

In [6]:
list = [1,2,3]
print(list)

list.append(4)
print(list)

list.append('abc')
print(list)
list = list + ['def']
print(list)

n='abc'
if n in list:
    print('{} 은 list 에 있다.'.format(n))

[1, 2, 3]
[1, 2, 3, 4]
[1, 2, 3, 4, 'abc']
[1, 2, 3, 4, 'abc', 'def']
abc 은 list 에 있다.


In [7]:
del list[0]
print(list)

del list[-1]
print(list)

print(list.pop())
print(list)

[2, 3, 4, 'abc', 'def']
[2, 3, 4, 'abc']
abc
[2, 3, 4]


In [8]:
# List comprehension

areas1 = [ i*i for i in range(1,11) ]
print(areas1)

areas2 = [ ( x, y ) for x in range(10) for y in range(10) ]
print('\n', areas2)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

 [(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (4, 9), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8), (5, 9), (6, 0), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6), (6, 7), (6, 8), (6, 9), (7, 0), (7, 1), (7, 2), (7, 3), (7, 4), (7, 5), (7, 6), (7, 7), (7, 8), (7, 9), (8, 0), (8, 1), (8, 2), (8, 3), (8, 4), (8, 5), (8, 6), (8, 7), (8, 8), (8, 9), (9, 0), (9, 1), (9, 2), (9, 3), (9, 4), (9, 5), (9, 6), (9, 7), (9, 8), (9, 9)]


## 3. Dictionary

In [9]:
dict = {
    "python": 0,
    "java":1,
    "c++":2,
    "ruby":3,
    "html":4,
}

print(dict)

for key, value in enumerate(dict):
    print('{} : {}'.format(key, value))

del dict["html"]
print(dict)

dict["pytorch"]=5
print(dict)

{'python': 0, 'java': 1, 'c++': 2, 'ruby': 3, 'html': 4}
0 : python
1 : java
2 : c++
3 : ruby
4 : html
{'python': 0, 'java': 1, 'c++': 2, 'ruby': 3}
{'python': 0, 'java': 1, 'c++': 2, 'ruby': 3, 'pytorch': 5}


## 4. Loop

In [10]:
numbers= [1, 2, 3, 4, 5]

for number in numbers:
    print(number)
      
languages = ['python', 'java', 'c++', 'ruby', 'html']

for i in range(len(languages)):
    language = languages[i]
    print('{}번 : {}'.format(i + 1, language))

1
2
3
4
5
1번 : python
2번 : java
3번 : c++
4번 : ruby
5번 : html


In [11]:
a=0
while(a<10):
    print(a)
    a+=1  

0
1
2
3
4
5
6
7
8
9


## 5. Condition

In [12]:
print(dict)

for key in dict:
    if key == 'pytorch':
        print('pytorch 는 {} 번이다.'.format(dict[key]))
    elif key == 'python':
        print('python 는 {} 번이다.'.format(dict[key]))
    else:
        print('not pytorch or python')

{'python': 0, 'java': 1, 'c++': 2, 'ruby': 3, 'pytorch': 5}
python 는 0 번이다.
not pytorch or python
not pytorch or python
not pytorch or python
pytorch 는 5 번이다.


## 6. Function

In [13]:
def factorial(num):
    result = 1
    for i in range(num):
        result = result*(i+1)
    return result

print(factorial(5))

120


## 7. Class and Inheritance

In [14]:
class Animal( ):
    def __init__( self, name ):
        self.name = name

class Human( Animal ):
    def __init__( self, name, hand ):
        super().__init__( name )
        self.hand = hand
        
    def wave(self):
        print('{}이 {}을 흔든다'.format(self.name, self.hand))

person = Human('홍길동', '오른손')
person.wave()

홍길동이 오른손을 흔든다


## 8. Module

In [15]:
import numpy as np

A = np.array([[4,2,1],[4,8,3],[1,1,0]])
print(A)

A_inverse = np.linalg.inv(A)
print(A_inverse)

print(np.dot(A, A_inverse))


# single line annotation

# multiple lines annotation by ''' as below,
'''
Note that this was meant to return the identity matrix, 
but that the float operations returned not zeros but numbers very close to zero.
'''

[[4 2 1]
 [4 8 3]
 [1 1 0]]
[[ 0.3 -0.1  0.2]
 [-0.3  0.1  0.8]
 [ 0.4  0.2 -2.4]]
[[ 1.00000000e+00 -2.77555756e-17  0.00000000e+00]
 [-1.66533454e-16  1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17 -1.38777878e-17  1.00000000e+00]]


'\nNote that this was meant to return the identity matrix, \nbut that the float operations returned not zeros but numbers very close to zero.\n'

## 9. Exception

In [16]:
B = np.array([[1,1,0],[2,2,0],[3,1,2]])
print(B)

try:
    B_inverse = np.linalg.inv(B)
    print(B_inverse)
    print(np.dot(B, B_inverse))
except:
    print('This matrix is not invertible.')

[[1 1 0]
 [2 2 0]
 [3 1 2]]
This matrix is not invertible.
